version: '3.3'

services:
  api:
    container_name: auth_usuarios.api
    build: ./app
    command : gunicorn auth_usuarios.wsgi:application --bind 0.0.0.0:3762
    volumes:
      - ./app:/usr/src/app
      - ./app/static:/usr/src/app/static
    ports:
      - 3762:3762
    env_file:
      - ./app/.env
  
  nginx:
    container_name: auth_usuarios.proxy
    build: ./nginx
    volumes:
      - ./app/static:/usr/src/app/static
    ports:
      - "80:80"
    depends_on:
      - api

volumes:
  static_volume:


